version: '2'

services:
        influx:
                image: influxdb
                volumes:
                        - influxdb:/var/lib/influxdb
                ports:
                        - "8086:8086"
                environment:
                        - INFLUXDB_GRAPHITE_ENABLED=true
        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
        pipeline:
                build: pipeline
                volumes:
                        - pipeline_data:/data
                        - running_pipeline_data:/running_data
                ports:
                        - "57500:57500"
        yang-explorer:
                image: hellt/yangexplorer-docker
                volumes:
                        - yangdata:/yang-explorer/server/data
                ports:
                        - "8088:8088"
volumes:
        influxdb:
        pipeline_data:
        running_pipeline_data:
        yangdata:
