version: '2'

services:
        influx:
                image: influxdb
                volumes:
                        - influxdb:/var/lib/influxdb
                ports:
                        - "8086:8086"
                environment:
                        - INFLUXDB_GRAPHITE_ENABLED=true
        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
                environment:
                        - GF_SMTP_HOST=outbound.cisco.com:25
                        - GF_SMTP_ENABLED=true
                        - GF_SMTP_SKIP_VERIFY=true
                        - GF_SMTP_FROM_NAME=Lab monitor
        telegraf:
                build: telegraf
                ports:
                        - "57500:57500"
                volumes:
                        - ./telegraf/data/config:/config
        rest-client:
                build: rest-client
                #image: fsedano/rest-client
                ports:
                        - "4000:4000"
                volumes:
                        - ./rest-client/target:/app:delegated
volumes:
        influxdb:
        running_pipeline_data:
        yangdata:
