version: '2'

services:
        influx:
                image: influxdb
                volumes:
                        - influxdb:/var/lib/influxdb
                environment:
                        - INFLUXDB_GRAPHITE_ENABLED=true
        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
                environment:
                        - GF_SMTP_HOST=outbound.cisco.com:25
                        - GF_SMTP_ENABLED=true
                        - GF_SMTP_SKIP_VERIFY=true
                        - GF_SMTP_FROM_NAME=Lab monitor
                        - HTTP_PROXY=
                        - HTTPS_PROXY=
                        - http_proxy=
                        - https_proxy=
                volumes:
                        - grafana:/var/lib/grafana
        telegraf:
                build: telegraf
                ports:
                        - "57500:57500"
                volumes:
                        - ./telegraf/data/config:/config
                environment:
                        - HTTP_PROXY=
                        - HTTPS_PROXY=
                        - http_proxy=
                        - https_proxy=

volumes:
        influxdb:
        running_pipeline_data:
