{
 "title": "Cisco Wireless",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "AP_MAC",
    "label": "AP MAC",
    "query": "SHOW TAG VALUES WITH KEY = \"wtp-mac\""
   },
   {
    "name": "CLIENT_MAC",
    "label": "Client MAC",
    "query": "SHOW TAG VALUES WITH KEY = \"ms-mac-address\""
   }
  ]
 },
 "panels": [
  {
   "title": "Rx bytes client",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
     "select": [
      [
       { "params": [ "bytes-rx" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "ms-mac-address", "operator": "=~", "value": "/^$CLIENT_MAC$/" }
     ]
    }
   ]
  },
  {
   "title": "Radio control",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "content": "<button class=\"btn btn-success\" onclick=\"start_ap1()\">Start AP1</button>\n<button class=\"btn btn-danger\" onclick=\"stop_ap1()\">Stop AP1</button>\n<hr>\n<button class=\"btn btn-success\" onclick=\"start_ap2()\">Start AP2</button>\n<button class=\"btn btn-danger\" onclick=\"stop_ap2()\">Stop AP2</button>\n\n<script>function start_ap1() {\n  var xhttp = new XMLHttpRequest();\n  xhttp.onreadystatechange = function() {\n    console.log(\"State change!. Ready=%o status=%o\", this.readyState, this.status);\n    if (this.readyState == 4 && this.status == 200) {\n      alert(\"JSON: \"+this.responseText)\n    }\n  }\n  var url = \"http://\"+window.location.hostname+\":4000/start_ap1\";\n  console.log(\"Sending UP to \"+ url);\n  xhttp.open(\"POST\", url, true);\n  xhttp.send();\n\n}\n</script>\n\n<script>function stop_ap1() {\n  var xhttp = new XMLHttpRequest();\n  xhttp.onreadystatechange = function() {\n    console.log(\"State change!. Ready=%o status=%o\", this.readyState, this.status);\n    if (this.readyState == 4 && this.status == 200) {\n      alert(\"JSON: \"+this.responseText)\n    }\n  }\n  var url = \"http://\"+window.location.hostname+\":4000/stop_ap1\"\n\n  xhttp.open(\"POST\", url, true);\n  xhttp.send();\n\n}\n</script>\n<script>function start_ap2() {\n  var xhttp = new XMLHttpRequest();\n  xhttp.onreadystatechange = function() {\n    console.log(\"State change!. Ready=%o status=%o\", this.readyState, this.status);\n    if (this.readyState == 4 && this.status == 200) {\n      alert(\"JSON: \"+this.responseText)\n    }\n  }\n  var url = \"http://\"+window.location.hostname+\":4000/start_ap2\"\n\n  xhttp.open(\"POST\", url, true);\n  xhttp.send();\n\n}\n</script>\n\n<script>function stop_ap2() {\n  var xhttp = new XMLHttpRequest();\n  xhttp.onreadystatechange = function() {\n    console.log(\"State change!. Ready=%o status=%o\", this.readyState, this.status);\n    if (this.readyState == 4 && this.status == 200) {\n      alert(\"JSON: \"+this.responseText)\n    }\n  }\n  var url = \"http://\"+window.location.hostname+\":4000/stop_ap2\"\n\n  xhttp.open(\"POST\", url, true);\n  xhttp.send();\n\n}\n</script>\n"
  },
  {
   "title": "Client RSSI",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Client RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
     "select": [
      [
       { "params": [ "most-recent-rssi" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "bottom"
       }
      ]
     ],
     "tags": [
      { "key": "ms-mac-address", "operator": "=~", "value": "/^$CLIENT_MAC$/" }
     ]
    }
   ]
  },
  {
   "title": "Ethernet traffic on AP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Ethernet traffic on AP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats",
     "select": [
      [
       { "params": [ "rx-total-bytes" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "if-index", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Radio channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Radio channel 2.4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/radio-oper-data",
     "select": [
      [
       {
        "params": [
         "phy-ht-cfg__cfg-data__curr-freq"
        ],
        "type": "field"
       },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "radio-slot-id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Radio channel 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/radio-oper-data",
     "select": [
      [
       {
        "params": [
         "phy-ht-cfg__cfg-data__curr-freq"
        ],
        "type": "field"
       },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "radio-slot-id", "operator": "=", "value": "1" }
     ]
    }
   ]
  }
 ]
}