{
 "title": "Cisco",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "CLIENT_MAC",
    "label": "Client MAC",
    "query": "show tag values with key = \"ms-mac-address\""
   },
   {
    "name": "AP_MAC",
    "label": "AP MAC",
    "query": "show tag values with key = \"wtp-mac\""
   },
   {
    "name": "wlan",
    "label": "WLAN",
    "query": "show tag values with key = \"wlan-profile\""
   }
  ]
 },
 "panels": [
  {
   "title": "Connected clients on WLAN $wlan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-mobility-oper:mobility-oper-data/wlan-client-limit",
     "select": [
      [
       { "params": [ "curr-clients-count" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wlan-profile", "operator": "=~", "value": "/^$wlan$/" }
     ]
    }
   ]
  },
  {
   "title": "Client $CLIENT_MAC RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Client RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
     "select": [
      [
       { "params": [ "most-recent-rssi" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "ms-mac-address", "operator": "=~", "value": "/^$CLIENT_MAC$/" }
     ]
    }
   ]
  },
  {
   "title": "AP Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Channel 2.4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/radio-oper-data",
     "select": [
      [
       {
        "params": [
         "phy-ht-cfg__cfg-data__curr-freq"
        ],
        "type": "field"
       },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "radio-slot-id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Channel 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/radio-oper-data",
     "select": [
      [
       {
        "params": [
         "phy-ht-cfg__cfg-data__curr-freq"
        ],
        "type": "field"
       },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "radio-slot-id", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "AP Ethernet traffix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 8 },
   "repeat": "AP_MAC",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RX packets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats",
     "select": [
      [
       { "params": [ "rx-pkts" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "if-name", "operator": "=", "value": "GigabitEthernet0" }
     ]
    },
    {
     "alias": "TX Packets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ethernet-if-stats",
     "select": [
      [
       { "params": [ "tx-pkts" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "wtp-mac", "operator": "=~", "value": "/^$AP_MAC$/" },
      { "condition": "AND", "key": "if-name", "operator": "=", "value": "GigabitEthernet0" }
     ]
    }
   ]
  }
 ]
}